receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200

  jaeger:
    endpoint: jaeger:14250
    insecure: true

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [ health_check ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ jaeger, logging ]